name: mupen64plus-gui # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.23.21' # just for humans, typically '1.2+git' or '1.3.2'
summary: Build of the Mupen64plus emulator with a GUI
description: |
  Build of the Mupen64plus emulator with a GUI

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  mupen64plus_icon.png
title: Mupen64plus (GUI)

apps:
  mupen64plus-gui:
    command: mupen64plus-gui
parts:
  mupen64plus-gui:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      mupen64plus-gui: build/
      mupen64plus-gui.1: man/man1/

architectures:
  - build-on: amd64

